name = "convergence-game-server"
main = "server/index.js"
compatibility_date = "2024-03-12"

[durable_objects]
bindings = [
  { name = "GAME_ROOM", class_name = "GameRoom" }
]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["GameRoom"]

[vars]
QUESTIONS = "[  \"Вы когда-нибудь хотели быть невидимым?\",  \"Вы бы предпочли жить в прошлом или в будущем?\",  \"Вы верите в судьбу?\",  \"Вы когда-нибудь спасали животное?\",  \"Вы бы хотели уметь летать?\",  \"Вы когда-нибудь пробовали экзотическую еду, которая вам не понравилась?\",  \"Вы бы предпочли иметь больше времени или больше денег?\",  \"Вы когда-нибудь терялись в незнакомом городе?\",  \"Вы верите в приметы?\",  \"Вы бы хотели прочитать мысли другого человека?\" ]"
