name = "convergence-game-server"
main = "server/index.js"
compatibility_date = "2024-03-12"

[durable_objects]
bindings = [
  { name = "GAME_ROOM", class_name = "GameRoom" }
]

[[kv_namespaces]]
binding = "GAME_IDS"
id = "9f643bf8cede4657aeaecbe7f6cf0141"

[[kv_namespaces]]
binding = "QUESTIONS_KV"
id = "b4904e9ae2154961bc1f6d0d55c2d536"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["GameRoom"]
